name = "StochasticPrograms"
uuid = "da0032aa-aa18-11e8-3e9c-4127ef7a7461"
authors = ["Martin Biel <martinbiel93@gmail.com>"]
version = "0.1.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MathProgBase = "fdba3010-5040-5b88-9595-932c9decdf73"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[extras]
GLPKMathProgInterface = "3c7084bd-78ad-589a-b5bb-dbd673274bea"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "GLPKMathProgInterface"]
